# Generated by Django 5.0.7 on 2024-07-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_seat_id_alter_seat_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='passenger_id',
            field=models.ForeignKey(default=None, on_delete=models.SET(None), related_name='seats', to='authentication.passenger'),
        ),
    ]
