# Generated by Django 5.0.7 on 2024-07-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_seat_passenger_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplanetype',
            name='business_rows',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airplanetype',
            name='economy_rows',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airplanetype',
            name='first_class_rows',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airplanetype',
            name='seats_per_business_row',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='airplanetype',
            name='seats_per_economy_row',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='airplanetype',
            name='seats_per_first_class_row',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='seat',
            name='passenger_id',
            field=models.ForeignKey(default=None, on_delete=models.SET(None), related_name='seat', to='authentication.passenger'),
        ),
    ]
