# Generated by Django 5.0.7 on 2024-07-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_airplanetype_business_rows_airplanetype_economy_rows_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='type',
        ),
        migrations.AlterField(
            model_name='seat',
            name='number',
            field=models.CharField(max_length=4),
        ),
    ]
