# Generated by Django 5.0.7 on 2024-07-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_seat_type_alter_seat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='passenger_id',
            field=models.ForeignKey(default=None, null=True, on_delete=models.SET(None), related_name='seat', to='authentication.passenger'),
        ),
    ]
