# Generated by Django 5.0.7 on 2024-07-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_seat_passenger_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arriving_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='date_of_flight',
            field=models.DateTimeField(),
        ),
    ]
