# Generated by Django 5.0.7 on 2024-07-30 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_flight_arriving_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=2, unique=True)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='OnboardService',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='additionalservices',
            name='place',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='company',
        ),
        migrations.AddField(
            model_name='airplane',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airplanes', to='authentication.company'),
        ),
        migrations.AddField(
            model_name='flight',
            name='base_business_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_class_services', to='authentication.additionalservices'),
        ),
        migrations.AddField(
            model_name='flight',
            name='base_economy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_services', to='authentication.additionalservices'),
        ),
        migrations.AddField(
            model_name='flight',
            name='base_first_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_class_services', to='authentication.additionalservices'),
        ),
        migrations.AlterField(
            model_name='additionalservices',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='additionalservices',
            name='services',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='authentication.order'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='authentication.seat'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='services',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket', to='authentication.additionalservices'),
        ),
        migrations.AlterField(
            model_name='additionalservices',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.meal'),
        ),
        migrations.AddField(
            model_name='additionalservices',
            name='services',
            field=models.ManyToManyField(to='authentication.onboardservice'),
        ),
    ]
