# Generated by Django 5.0.7 on 2024-07-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_meal_onboardservice_remove_additionalservices_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalservices',
            name='baggage_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='additionalservices',
            name='hand_luggage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meal',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='onboardservice',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
