# Generated by Django 5.0.7 on 2024-07-30 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_additionalservices_baggage_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='code',
        ),
    ]
