# Generated by Django 5.0.7 on 2024-07-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_remove_meal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalservices',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
