# Generated by Django 5.0.7 on 2024-07-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_additionalservices_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='business_seat_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='economy_seat_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='first_seat_price',
            field=models.FloatField(default=0),
        ),
    ]
