# Generated by Django 5.0.7 on 2024-08-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_flight_business_seat_price_flight_economy_seat_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
