# Generated by Django 5.0.7 on 2024-08-08 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_seat_booked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baggage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('height', models.FloatField(default=0)),
                ('width', models.FloatField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('number', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HandLuggage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('height', models.FloatField(default=0)),
                ('width', models.FloatField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('number', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='available_services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_services', to='authentication.additionalservices'),
        ),
    ]
