# Generated by Django 5.0.7 on 2024-08-08 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_baggage_handluggage_flight_available_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalservices',
            name='baggage_weight',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='passport_id',
        ),
        migrations.AddField(
            model_name='additionalservices',
            name='baggage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service', to='authentication.baggage'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Undisclosed')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='additionalservices',
            name='hand_luggage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='authentication.baggage'),
        ),
    ]
