# Generated by Django 5.0.7 on 2024-08-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_remove_flight_available_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='available_services',
            field=models.ManyToManyField(related_name='flight_services', to='authentication.onboardservice'),
        ),
    ]
